from os import *

files = listdir("E:\DESK\Fotos\RAW")

files = files[6:68]
files.pop(5)
for i in files:
    with open("listas\{img}.txt".format(img = i),"w",encoding = 'utf8') as n:
        n.writelines(["DSS file list","\n","CHECKED	TYPE	FILE","\n"])
        n.writelines(["1	light	E:\DESK\Fotos\RAW\{img}".format(img=i),"\n",
                      "1	dark	E:\DESK\Fotos\Astrofotografía\Astrofoto T3\Calibration frames\Darks 30s 1600iso\MasterDark_ISO1600_30s.tif",
                      "\n",
                      "1	offset	E:\DESK\Fotos\Astrofotografía\Astrofoto T3\Calibration frames\Bias 1600iso\MasterOffset_ISO1600.tif",
                      "\n", "#WS#Software\DeepSkyStacker\FitsDDP|BayerPattern=4","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|BlueScale=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|Brighness=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|DSLR=RGGB Genérico","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|FITSisRAW=0","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|ForceUnsigned=0","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|Interpolation=Bilinear","\n",
                        "#WS#Software\DeepSkyStacker\FitsDDP|RedScale=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|AHD=0","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|BlackPointTo0=1","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|BlueScale=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|Brighness=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|CameraWB=1","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|Interpolation=Bilinear","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|NoWB=0","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|RawBayer=0","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|RedScale=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\RawDDP|SuperPixels=0","\n",
                        "#WS#Software\DeepSkyStacker\Register|ApplyMedianFilter=1","\n",
                        "#WS#Software\DeepSkyStacker\Register|DetectHotPixels=1","\n",
                        "#WS#Software\DeepSkyStacker\Register|DetectionThreshold=45","\n",
                        "#WS#Software\DeepSkyStacker\Register|PercentStack=60","\n",
                        "#WS#Software\DeepSkyStacker\Register|StackAfter=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|AlignChannels=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|AlignmentTransformation=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|ApplyFilterToCometImages=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|BackgroundCalibration=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|BackgroundCalibrationInterpolation=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|BadLinesDetection=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|CometStackingMode=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|CreateIntermediates=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|DarkFactor=1.0000","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|DarkOptimization=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Dark_Iteration=5","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Dark_Kappa=2.0000","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Dark_Method=2","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Debloom=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Flat_Iteration=5","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Flat_Kappa=2.0000","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Flat_Method=2","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|HotPixelsDetection=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|IntermediateFileFormat=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Light_Iteration=5","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Light_Kappa=2.0000","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Light_Method=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|LockCorners=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Mosaic=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Offset_Iteration=5","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Offset_Kappa=2.0000","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|Offset_Method=2","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_ColdDetection=500","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_ColdFilter=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_DetectCleanCold=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_DetectCleanHot=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_HotDetection=500","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_HotFilter=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_ReplaceMethod=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PCS_SaveDeltaImage=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PerChannelBackgroundCalibration=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|PixelSizeMultiplier=1","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|RGBBackgroundCalibrationMethod=2","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|SaveCalibrated=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|SaveCalibratedDebayered=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|SaveCometImages=0","\n",
                        "#WS#Software\DeepSkyStacker\Stacking|UseDarkFactor=0","\n"])